apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: chatapp
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: chatapp
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: chatapp
        tier: frontend
    spec:
      containers:
      - name: webapp
        image: noelberistain/react
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]