export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_LOGOUT = 'USER_LOGOUT';

export const CONTACTS_LOADING = 'CONTACTS_LOADING';

export const ADD_FRIEND = 'ADD_FRIEND';
export const GET_FRIENDS = 'GET_FRIENDS';
export const DELETE_FRIEND = 'DELETE_FRIEND';

export const CREATE_CONVERSATION = 'CREATE_CONVERSATION';
export const GET_CONVERSATION_ID = 'GET_CONVERSATION_ID';

export const GET_MESSAGES = 'GET_MESSAGES';
export const NEW_MESSAGE = 'NEW_MESSAGE';

export const ADD_NAME_GROUP = 'ADD_NAME_GROUP';
export const ADD_GROUP_CONTACT = 'ADD_GROUP_CONTACT';
export const REMOVE_GROUP_CONTACT = 'REMOVE_GROUP_CONTACT';
export const RESTORE_DEFAULT = 'RESTORE_DEFAULT';
export const CREATE_GROUP = 'CREATE_GROUP';
export const GET_GROUPS = 'GET_GROUPS';
export const GET_GROUP_MESSAGES = 'GET_GROUP_MESSAGES';

export const SET_LANG = 'SET_LANG';
export const NOTHING = 'NOTHING';