export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const CONTACTS_LOADING = 'CONTACTS_LOADING';

export const ADD_FRIEND = 'ADD_FRIEND';
export const GET_FRIENDS = 'GET_FRIENDS';
export const DELETE_FRIEND = 'DELETE_FRIEND';

export const CREATE_CONVERSATION = 'CREATE_CONVERSATION';
export const GET_CONVERSATION_ID = 'GET_CONVERSATION_ID';